// Mock data for frontend demo - will be replaced with Supabase data

export const categories = [
  {
    id: "1",
    name: "Wall Tiles",
    slug: "wall-tiles",
    description: "Premium wall tiles for kitchens, bathrooms, and living spaces",
    image: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&q=80",
    productCount: 45,
  },
  {
    id: "2",
    name: "Floor Tiles",
    slug: "floor-tiles",
    description: "Durable floor tiles for every room in your home",
    image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80",
    productCount: 38,
  },
  {
    id: "3",
    name: "Outdoor Tiles",
    slug: "outdoor-tiles",
    description: "Weather-resistant tiles for patios, gardens, and driveways",
    image: "https://images.unsplash.com/photo-1600566752229-250ed79470f8?w=800&q=80",
    productCount: 24,
  },
  {
    id: "4",
    name: "PVC Panels",
    slug: "pvc-panels",
    description: "Easy-install PVC wall panels for bathrooms and kitchens",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
    productCount: 18,
  },
  {
    id: "5",
    name: "Acoustic Panels",
    slug: "acoustic-panels",
    description: "Sound-absorbing panels for offices and home studios",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
    productCount: 12,
  },
  {
    id: "6",
    name: "SPC Flooring",
    slug: "spc-flooring",
    description: "Stone Plastic Composite flooring - waterproof and durable",
    image: "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&q=80",
    productCount: 22,
  },
  {
    id: "7",
    name: "Accessories",
    slug: "accessories",
    description: "Tile adhesives, grout, trims, and installation tools",
    image: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&q=80",
    productCount: 35,
  },
]

export const products = [
  // Wall Tiles
  {
    id: "1",
    name: "Mosaica White Marble Effect",
    slug: "mosaica-white-marble-effect",
    description: "Elegant white marble effect wall tile. Perfect for creating a luxurious bathroom or kitchen backsplash. The subtle veining adds depth and character to any space.",
    price: 24.99,
    compareAtPrice: 29.99,
    category: "wall-tiles",
    categoryName: "Wall Tiles",
    images: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
      "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&q=80",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80",
    ],
    sku: "WT-MOS-001",
    stock: 150,
    isFeatured: true,
    specifications: {
      size: "300 x 600mm",
      thickness: "9mm",
      finish: "Gloss",
      material: "Ceramic",
      coverage: "1.44m² per box",
      suitability: "Wall only",
    },
  },
  {
    id: "2",
    name: "Metro Grey Gloss",
    slug: "metro-grey-gloss",
    description: "Classic metro tile in grey gloss finish. Timeless design that works in any space, from traditional to contemporary. Easy to clean and maintain.",
    price: 18.99,
    compareAtPrice: null,
    category: "wall-tiles",
    categoryName: "Wall Tiles",
    images: [
      "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
    ],
    sku: "WT-MET-002",
    stock: 200,
    isFeatured: true,
    specifications: {
      size: "100 x 200mm",
      thickness: "7mm",
      finish: "Gloss",
      material: "Ceramic",
      coverage: "1m² per box",
      suitability: "Wall only",
    },
  },
  {
    id: "3",
    name: "Terrazzo Effect Blue",
    slug: "terrazzo-effect-blue",
    description: "Modern terrazzo effect tile with blue chips. Add a pop of colour and texture to your space with this contemporary design.",
    price: 32.99,
    compareAtPrice: 39.99,
    category: "wall-tiles",
    categoryName: "Wall Tiles",
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
    ],
    sku: "WT-TER-003",
    stock: 80,
    isFeatured: false,
    specifications: {
      size: "450 x 450mm",
      thickness: "10mm",
      finish: "Matt",
      material: "Porcelain",
      coverage: "1.62m² per box",
      suitability: "Wall & Floor",
    },
  },
  {
    id: "4",
    name: "Brick White Matt",
    slug: "brick-white-matt",
    description: "Contemporary white brick effect wall tile. Create an industrial or Scandinavian look with these versatile tiles.",
    price: 21.99,
    compareAtPrice: null,
    category: "wall-tiles",
    categoryName: "Wall Tiles",
    images: [
      "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&q=80",
    ],
    sku: "WT-BRK-004",
    stock: 300,
    isFeatured: true,
    specifications: {
      size: "60 x 250mm",
      thickness: "8mm",
      finish: "Matt",
      material: "Ceramic",
      coverage: "0.9m² per box",
      suitability: "Wall only",
    },
  },
  // Floor Tiles
  {
    id: "5",
    name: "Oak Wood Effect",
    slug: "oak-wood-effect",
    description: "Natural oak wood effect floor tile. Authentic grain pattern that brings warmth to any room. Durable and easy to maintain - perfect for high traffic areas.",
    price: 28.99,
    compareAtPrice: 34.99,
    category: "floor-tiles",
    categoryName: "Floor Tiles",
    images: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
    ],
    sku: "FT-OAK-001",
    stock: 250,
    isFeatured: true,
    specifications: {
      size: "200 x 1200mm",
      thickness: "10mm",
      finish: "Matt",
      material: "Porcelain",
      coverage: "1.44m² per box",
      suitability: "Wall & Floor",
      slipRating: "R10",
    },
  },
  {
    id: "6",
    name: "Slate Grey Matt",
    slug: "slate-grey-matt",
    description: "Natural slate effect in grey. Anti-slip R10 rating makes it perfect for kitchens, bathrooms, and hallways.",
    price: 26.99,
    compareAtPrice: null,
    category: "floor-tiles",
    categoryName: "Floor Tiles",
    images: [
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&q=80",
    ],
    sku: "FT-SLA-002",
    stock: 180,
    isFeatured: true,
    specifications: {
      size: "600 x 600mm",
      thickness: "10mm",
      finish: "Matt",
      material: "Porcelain",
      coverage: "1.44m² per box",
      suitability: "Wall & Floor",
      slipRating: "R10",
    },
  },
  {
    id: "7",
    name: "Concrete Industrial",
    slug: "concrete-industrial",
    description: "Urban concrete effect floor tile. Perfect for creating a modern industrial aesthetic in any space.",
    price: 24.99,
    compareAtPrice: null,
    category: "floor-tiles",
    categoryName: "Floor Tiles",
    images: [
      "https://images.unsplash.com/photo-1600566752734-2a0cd66c42ee?w=800&q=80",
    ],
    sku: "FT-CON-003",
    stock: 220,
    isFeatured: false,
    specifications: {
      size: "600 x 600mm",
      thickness: "10mm",
      finish: "Matt",
      material: "Porcelain",
      coverage: "1.44m² per box",
      suitability: "Wall & Floor",
      slipRating: "R10",
    },
  },
  {
    id: "8",
    name: "Marble Nero",
    slug: "marble-nero",
    description: "Luxurious black marble effect floor tile. Make a bold statement with these stunning tiles featuring dramatic white veining.",
    price: 42.99,
    compareAtPrice: 49.99,
    category: "floor-tiles",
    categoryName: "Floor Tiles",
    images: [
      "https://images.unsplash.com/photo-1600585153490-76fb20a32601?w=800&q=80",
    ],
    sku: "FT-MAR-004",
    stock: 90,
    isFeatured: true,
    specifications: {
      size: "800 x 800mm",
      thickness: "10mm",
      finish: "Polished",
      material: "Porcelain",
      coverage: "1.28m² per box",
      suitability: "Wall & Floor",
    },
  },
  // Outdoor Tiles
  {
    id: "9",
    name: "Porcelain Paving Grey",
    slug: "porcelain-paving-grey",
    description: "Premium porcelain paving slab. Frost-proof and incredibly durable, perfect for patios, paths, and outdoor entertaining areas.",
    price: 34.99,
    compareAtPrice: null,
    category: "outdoor-tiles",
    categoryName: "Outdoor Tiles",
    images: [
      "https://images.unsplash.com/photo-1600566752229-250ed79470f8?w=800&q=80",
    ],
    sku: "OT-PAV-001",
    stock: 400,
    isFeatured: true,
    specifications: {
      size: "600 x 600 x 20mm",
      thickness: "20mm",
      finish: "Matt",
      material: "Porcelain",
      coverage: "0.36m² per tile",
      suitability: "Outdoor",
      slipRating: "R11",
    },
  },
  {
    id: "10",
    name: "Sandstone Effect Beige",
    slug: "sandstone-effect-beige",
    description: "Natural sandstone effect outdoor tile. Warm beige tones complement any garden design.",
    price: 32.99,
    compareAtPrice: 38.99,
    category: "outdoor-tiles",
    categoryName: "Outdoor Tiles",
    images: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80",
    ],
    sku: "OT-SAN-002",
    stock: 350,
    isFeatured: false,
    specifications: {
      size: "600 x 600 x 20mm",
      thickness: "20mm",
      finish: "Textured",
      material: "Porcelain",
      coverage: "0.36m² per tile",
      suitability: "Outdoor",
      slipRating: "R11",
    },
  },
  {
    id: "11",
    name: "Decking Tiles Composite",
    slug: "decking-tiles-composite",
    description: "Easy-click composite decking tiles. Transform your balcony or terrace in minutes with these interlocking tiles. Pack of 6.",
    price: 44.99,
    compareAtPrice: null,
    category: "outdoor-tiles",
    categoryName: "Outdoor Tiles",
    images: [
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80",
    ],
    sku: "OT-DEC-003",
    stock: 120,
    isFeatured: true,
    specifications: {
      size: "300 x 300mm (pack of 6)",
      thickness: "22mm",
      finish: "Wood grain",
      material: "WPC Composite",
      coverage: "0.54m² per pack",
      suitability: "Outdoor",
    },
  },
  // PVC Panels
  {
    id: "12",
    name: "Marble Effect White Panel",
    slug: "marble-effect-white-panel",
    description: "Waterproof PVC panel with stunning marble effect. Quick and easy installation - no grouting required. Perfect for shower walls and bathroom feature walls.",
    price: 49.99,
    compareAtPrice: 59.99,
    category: "pvc-panels",
    categoryName: "PVC Panels",
    images: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
    ],
    sku: "PVC-MAR-001",
    stock: 75,
    isFeatured: true,
    specifications: {
      size: "1000 x 2400mm",
      thickness: "10mm",
      finish: "High Gloss",
      material: "PVC",
      coverage: "2.4m² per panel",
      suitability: "Wall only (wet areas)",
    },
  },
  {
    id: "13",
    name: "Tile Effect Grey Panel",
    slug: "tile-effect-grey-panel",
    description: "PVC panel with realistic tile effect. Get the look of tiles without the hassle of grouting.",
    price: 44.99,
    compareAtPrice: null,
    category: "pvc-panels",
    categoryName: "PVC Panels",
    images: [
      "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&q=80",
    ],
    sku: "PVC-TIL-002",
    stock: 85,
    isFeatured: false,
    specifications: {
      size: "1000 x 2400mm",
      thickness: "10mm",
      finish: "Matt",
      material: "PVC",
      coverage: "2.4m² per panel",
      suitability: "Wall only (wet areas)",
    },
  },
  // SPC Flooring
  {
    id: "14",
    name: "SPC Oak Natural",
    slug: "spc-oak-natural",
    description: "Waterproof SPC flooring in natural oak. 5mm thick with built-in underlay. Click-lock installation for easy DIY fitting.",
    price: 22.99,
    compareAtPrice: 27.99,
    category: "spc-flooring",
    categoryName: "SPC Flooring",
    images: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80",
    ],
    sku: "SPC-OAK-001",
    stock: 500,
    isFeatured: true,
    specifications: {
      size: "180 x 1220mm",
      thickness: "5mm (inc. underlay)",
      finish: "Embossed",
      material: "SPC (Stone Plastic Composite)",
      coverage: "2.2m² per pack",
      suitability: "All rooms inc. bathrooms",
    },
  },
  {
    id: "15",
    name: "SPC Herringbone Grey",
    slug: "spc-herringbone-grey",
    description: "Herringbone pattern SPC flooring in grey. Make a statement with this classic pattern in a modern finish.",
    price: 28.99,
    compareAtPrice: null,
    category: "spc-flooring",
    categoryName: "SPC Flooring",
    images: [
      "https://images.unsplash.com/photo-1600566752734-2a0cd66c42ee?w=800&q=80",
    ],
    sku: "SPC-HER-002",
    stock: 320,
    isFeatured: true,
    specifications: {
      size: "120 x 600mm",
      thickness: "6mm (inc. underlay)",
      finish: "Embossed",
      material: "SPC (Stone Plastic Composite)",
      coverage: "1.73m² per pack",
      suitability: "All rooms inc. bathrooms",
    },
  },
  // Accessories
  {
    id: "16",
    name: "Tile Adhesive 20kg",
    slug: "tile-adhesive-20kg",
    description: "Premium flexible tile adhesive. Suitable for walls and floors, indoor and outdoor use. S1 rated for added flexibility.",
    price: 18.99,
    compareAtPrice: null,
    category: "accessories",
    categoryName: "Accessories",
    images: [
      "https://images.unsplash.com/photo-1600566752229-250ed79470f8?w=800&q=80",
    ],
    sku: "ACC-ADH-001",
    stock: 150,
    isFeatured: false,
    specifications: {
      weight: "20kg",
      coverage: "4-5m² (depending on trowel size)",
      setTime: "24 hours",
      suitability: "Wall & Floor, Indoor & Outdoor",
    },
  },
  {
    id: "17",
    name: "Grout Anthracite 5kg",
    slug: "grout-anthracite-5kg",
    description: "Flexible wall and floor grout in anthracite. Mould resistant formula perfect for bathrooms and kitchens.",
    price: 12.99,
    compareAtPrice: null,
    category: "accessories",
    categoryName: "Accessories",
    images: [
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&q=80",
    ],
    sku: "ACC-GRT-002",
    stock: 200,
    isFeatured: false,
    specifications: {
      weight: "5kg",
      coverage: "8-10m² (3mm joints)",
      colours: "Anthracite",
      suitability: "Wall & Floor",
    },
  },
  {
    id: "18",
    name: "Tile Trim Chrome 2.5m",
    slug: "tile-trim-chrome-2-5m",
    description: "Chrome tile trim for neat edge finishing. Professional look for exposed tile edges.",
    price: 8.99,
    compareAtPrice: null,
    category: "accessories",
    categoryName: "Accessories",
    images: [
      "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&q=80",
    ],
    sku: "ACC-TRM-003",
    stock: 300,
    isFeatured: false,
    specifications: {
      length: "2.5m",
      depth: "10mm",
      material: "Aluminium with chrome finish",
    },
  },
]

export function getProductsByCategory(categorySlug: string) {
  return products.filter((p) => p.category === categorySlug)
}

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug)
}

export function getCategoryBySlug(slug: string) {
  return categories.find((c) => c.slug === slug)
}

export function getFeaturedProducts() {
  return products.filter((p) => p.isFeatured)
}

export function getAllProducts() {
  return products
}

export function searchProducts(query: string) {
  const q = query.toLowerCase()
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.categoryName.toLowerCase().includes(q)
  )
}
